default: &default
  adapter: postgresql
  encoding: unicode
  username: tester
  password: kek
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test


test:
  <<: *default
  database: test